admin_email: admin@example.com
title: title
admin_user: admin_user

plugins:
  - advanced-custom-fields
  - all-in-one-seo-pack
  - classic-editor
  - custom-post-type-permalinks
  - duplicate-post
  - intuitive-custom-post-order
  - regenerate-thumbnails
  - smart-custom-fields
  - tinymce-advanced
  - wp-multibyte-patch
  - wp-serverinfo
  - wp-sweep
